USE [Compliance]
GO
/****** Object:  Table [dbo].[TBL_EM_EMPLOYEES]    Script Date: 23-12-2020 23:09:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_EM_EMPLOYEES](
	[ID] [int] NOT NULL,
	[CODE] [varchar](50) NULL,
	[CARDNO] [varchar](50) NULL,
	[SALUTATION] [int] NULL,
	[FIRSTNAME] [varchar](50) NULL,
	[MIDDLENAME] [varchar](50) NULL,
	[LASTNAME] [varchar](50) NULL,
	[FATHERNAME] [varchar](50) NULL,
	[DATEOFBIRTH] [datetime] NULL,
	[DATEOFJOINING] [datetime] NULL,
	[GENDER] [char](1) NULL,
	[MARITALSTATUS] [int] NULL,
	[WEDANNIVERSARY] [datetime] NULL,
	[BLOODGROUP] [int] NULL,
	[NATIONALITYID] [int] NULL,
	[ETHNICRACEID] [int] NULL,
	[CASTID] [int] NULL,
	[TYPEID] [int] NULL,
	[ISSMOKER] [char](1) NULL,
	[ISHANDICAPPED] [int] NULL,
	[ISACTIVE] [char](1) NULL,
	[ISSETTLEMENT] [char](1) NULL,
	[HEIGHT] [varchar](10) NULL,
	[WEIGHT] [varchar](10) NULL,
	[REJOINDATE] [datetime] NULL,
	[REJOINREMARK] [varchar](800) NULL,
	[MAKERCHECKER] [char](1) NULL,
	[ISMCHECKERAPPROVED] [int] NULL,
	[COMPANYID] [int] NULL,
	[DIVISIONID] [int] NULL,
	[BRANCHID] [int] NULL,
	[CREATEDBY] [int] NOT NULL,
	[CREATEDDATE] [datetime] NOT NULL,
	[MODIFIEDBY] [int] NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[FULLNAME] [varchar](160) NULL,
	[CANDIDATEID] [int] NULL,
	[ISINTERNAL] [int] NULL,
	[ISPEOPLEOFFICER] [int] NULL,
	[REQUESTID] [int] NULL,
	[SUBREQUESTID] [int] NULL,
	[PERMANENTNO] [varchar](50) NULL,
	[CELEBRATIONDATE] [datetime] NULL,
	[KNOWNASNAME] [varchar](200) NULL,
	[ASSISTANTTO] [int] NULL,
	[AADHAARNUMBER] [varchar](50) NULL,
	[PATHSHALA_SYNC] [varchar](100) NULL,
	[TIMESTAMP] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBL_MST_BRANCH]    Script Date: 23-12-2020 23:09:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_MST_BRANCH](
	[BRANCH_ID] [nchar](10) NOT NULL,
	[BRANCH_NAME] [nchar](10) NULL,
	[ISACTIVE] [nchar](10) NULL,
 CONSTRAINT [PK_TBL_MST_BRANCH] PRIMARY KEY CLUSTERED 
(
	[BRANCH_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBL_MST_CATEGORIES]    Script Date: 23-12-2020 23:09:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_MST_CATEGORIES](
	[CATEGORY_ID] [nchar](10) NOT NULL,
	[CATEGORY_NAME] [nchar](10) NULL,
	[CATEGORY_DETAILS] [nchar](10) NULL,
	[ISACTIVE] [bit] NULL,
 CONSTRAINT [PK_TBL_MST_CATEGORIES] PRIMARY KEY CLUSTERED 
(
	[CATEGORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBL_MST_DOCUMENT_TYPES]    Script Date: 23-12-2020 23:09:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_MST_DOCUMENT_TYPES](
	[DOCUMENT_TYPE_ID] [nchar](10) NOT NULL,
	[DOCUMENT_TYPE_NAME] [nchar](10) NULL,
	[DOCUMENT_TYPE_DETAILS] [nchar](10) NULL,
	[ISACTIVE] [bit] NULL,
 CONSTRAINT [PK_TBL_MST_DOCUMENT_TYPES] PRIMARY KEY CLUSTERED 
(
	[DOCUMENT_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBL_MST_ROLES]    Script Date: 23-12-2020 23:09:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_MST_ROLES](
	[Role_Id] [int] NOT NULL,
	[Role_Name] [varchar](50) NULL,
	[Role_Description] [varchar](50) NULL,
 CONSTRAINT [PK_tbl_mst_role] PRIMARY KEY CLUSTERED 
(
	[Role_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
